project:
  type: website
  output-dir: docs #added so github automatically makes site

website:
  title: "Raul E"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: darkly
    css: styles.css

editor: visual

